version: '3'

services:
  db:
    image: shurdanil/wheather:postgres
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=weather
    ports:
      - "5432:5432"
  django:
    image: shurdanil/wheather:django
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    image: shurdanil/wheather:frontend
    ports:
      - "3000:3000"
